/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./src/components/homePageSet/album.vue')['default']
    Charts: typeof import('./src/components/homePageSet/charts.vue')['default']
    ClassifiedPlaylist: typeof import('./src/components/homePageSet/classifiedList/classifiedPlaylist.vue')['default']
    Client: typeof import('./src/components/headerPopover/client.vue')['default']
    DefaultLayout: typeof import('./src/components/defaultLayout.vue')['default']
    DetailsTemplate: typeof import('./src/components/detailsTemplate.vue')['default']
    DigitalAlbum: typeof import('./src/components/homePageSet/digitalAlbum.vue')['default']
    HeaderNav: typeof import('./src/components/header-nav.vue')['default']
    HeadPage: typeof import('./src/components/homePageSet/headPage/headPage.vue')['default']
    HomePageClassification: typeof import('./src/components/headerFeatures/home-page-classification.vue')['default']
    ImgLyrics: typeof import('./src/components/playerInterface/imgLyrics.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    LoginVipCharge: typeof import('./src/components/headerFeatures/loginVipCharge.vue')['default']
    MV: typeof import('./src/components/homePageSet/MV.vue')['default']
    MyMusic: typeof import('./src/components/myMusic.vue')['default']
    NewAlbumCategory: typeof import('./src/components/homePageSet/headPage/newAlbumPublish/newAlbumCategory.vue')['default']
    NewsongCategories: typeof import('./src/components/homePageSet/headPage/newSongPublish/newsongCategories.vue')['default']
    PlayControls: typeof import('./src/components/playControls.vue')['default']
    PlayCover: typeof import('./src/components/playCover.vue')['default']
    PlaylistItem: typeof import('./src/components/homePageSet/headPage/recommendation/playlistItem.vue')['default']
    PlaylistRecommendation: typeof import('./src/components/playlistRecommendation.vue')['default']
    Playlists: typeof import('./src/components/songlist/playlists.vue')['default']
    Portrait: typeof import('./src/components/headerFeatures/portrait.vue')['default']
    Radio: typeof import('./src/components/homePageSet/radio.vue')['default']
    Ranking: typeof import('./src/components/homePageSet/headPage/rankingList/ranking.vue')['default']
    RankingItem: typeof import('./src/components/homePageSet/headPage/rankingList/rankingItem.vue')['default']
    RecommendationTitle: typeof import('./src/components/homePageSet/headPage/recommendation/recommendationTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/headerFeatures/search.vue')['default']
    Singer: typeof import('./src/components/homePageSet/singer.vue')['default']
    SongDetails: typeof import('./src/components/songDetails/songDetails.vue')['default']
    SonglistDetails: typeof import('./src/components/songlist/songlistDetails.vue')['default']
    SongLyrics: typeof import('./src/components/songDetails/songLyrics.vue')['default']
    SongPlay: typeof import('./src/components/playerInterface/index.vue')['default']
    UserInformation: typeof import('./src/components/headerPopover/userInformation.vue')['default']
    WheelButton: typeof import('./src/components/wheelButton.vue')['default']
    WheelCatogories: typeof import('./src/components/homePageSet/classifiedList/wheelCatogories.vue')['default']
    WheelContainer: typeof import('./src/components/homePageSet/headPage/recommendation/wheelContainer.vue')['default']
    WheelExcellentRecommendation: typeof import('./src/components/homePageSet/headPage/excellentRecommendation/wheelExcellentRecommendation.vue')['default']
    WheelPlayNewAlbum: typeof import('./src/components/homePageSet/headPage/newAlbumPublish/wheelPlayNewAlbum.vue')['default']
    WheelplayNewSong: typeof import('./src/components/homePageSet/headPage/newSongPublish/wheelplayNewSong.vue')['default']
  }
}
