export const PROGRAM_CHANGE_TO_SOUNDBANK = {
  0: {
    name: "Acoustic Grand Piano",
    soundbank: "studio-grand",
  },
  1: {
    name: "Bright Acoustic Piano",
    soundbank: "upright-piano",
  },
  2: {
    name: "Electric Grand Piano",
    soundbank: "grand-piano",
  },
  3: {
    name: "Honky-tonk Piano",
    soundbank: "honky-tonk-piano",
  },
  4: {
    name: "Electric Piano 01",
    soundbank: "electric-piano",
  },
  5: {
    name: "Electric Piano 02",
    soundbank: "electric-piano",
  },
  6: {
    name: "Harpsichord",
    soundbank: "studio-harpsichord",
  },
  7: {
    name: "Clavi",
    soundbank: "funky-tone",
  },
  8: {
    name: "Celesta",
    soundbank: "vibraphone",
  },
  9: {
    name: "Glockenspiel",
    soundbank: "glockenspiel",
  },
  10: {
    name: "Music Box",
    soundbank: "vibraphone",
  },
  11: {
    name: "Vibraphone",
    soundbank: "vibraphone",
  },
  12: {
    name: "Marimba",
    soundbank: "marimba",
  },
  13: {
    name: "Xylophone",
    soundbank: "xylophone",
  },
  14: {
    name: "Tubular Bells",
    soundbank: "tubular-bells",
  },
  15: {
    name: "Dulcimer",
    soundbank: "hammered-dulcimer",
  },
  16: {
    name: "Drawbar Organ",
    soundbank: "dark-organ",
  },
  17: {
    name: "Percussive Organ",
    soundbank: "fanfare-organ",
  },
  18: {
    name: "Rock Organ",
    soundbank: "rock-organ",
  },
  19: {
    name: "Church Organ",
    soundbank: "church-organ",
  },
  20: {
    name: "Reed Organ",
    soundbank: "dark-organ",
  },
  21: {
    name: "Accordion",
    soundbank: "accordion",
  },
  22: {
    name: "Harmonica",
    soundbank: "harmonica",
  },
  23: {
    name: "Tango Accordion",
    soundbank: "accordion",
  },
  24: {
    name: "Acoustic Guitar (Nylon)",
    soundbank: "nylon-guitar",
  },
  25: {
    name: "Acoustic Guitar (Steel)",
    soundbank: "sparkling-acoustic",
  },
  26: {
    name: "Electric Guitar (Jazz)",
    soundbank: "jazz-guitar",
  },
  27: {
    name: "Electric Guitar (Clean)",
    soundbank: "clean-guitar",
  },
  28: {
    name: "Electric Guitar (Muted)",
    soundbank: "clean-guitar-muted",
  },
  29: {
    name: "Overdriven Guitar",
    soundbank: "overdriven-guitar",
  },
  30: {
    name: "Distortion Guitar",
    soundbank: "overdriven-power-chord",
  },
  31: {
    name: "Guitar Harmonics",
    soundbank: "guitar-power-chord",
  },
  32: {
    name: "Acoustic Bass",
    soundbank: "acoustic-bass-legato",
  },
  33: {
    name: "Electric Bass (Finger)",
    soundbank: "62-p-bass",
  },
  34: {
    name: "Electric Bass (Pick)",
    soundbank: "retro-pick-bass",
  },
  35: {
    name: "Fretless Bass",
    soundbank: "dub-bass",
  },
  36: {
    name: "Slap Bass 01",
    soundbank: "slap-bass",
  },
  37: {
    name: "Slap Bass 02",
    soundbank: "funky-slap",
  },
  38: {
    name: "Synth Bass 01",
    soundbank: "deep-house-bass",
  },
  39: {
    name: "Synth Bass 02",
    soundbank: "plucked-vaporbass",
  },
  40: {
    name: "Violin",
    soundbank: "solo-violin",
  },
  41: {
    name: "Viola",
    soundbank: "viola-section",
  },
  42: {
    name: "Cello",
    soundbank: "cello-section",
  },
  43: {
    name: "Contrabass",
    soundbank: "double-bass-section",
  },
  44: {
    name: "Tremolo Strings",
    soundbank: "full-strings-tremolo",
  },
  45: {
    name: "Pizzicato Strings",
    soundbank: "full-strings-pizzicato",
  },
  46: {
    name: "Orchestral Harp",
    soundbank: "harp",
  },
  47: {
    name: "Timpani",
    soundbank: "timpani",
  },
  48: {
    name: "String Ensemble 01",
    soundbank: "string-orchestra",
  },
  49: {
    name: "String Ensemble 02",
    soundbank: "string-orchestra",
  },
  50: {
    name: "Synth String 01",
    soundbank: "synth-strings",
  },
  51: {
    name: "Synth String 02",
    soundbank: "string-pad",
  },
  52: {
    name: "Choir Ahhs",
    soundbank: "choir-synth",
  },
  53: {
    name: "Voice Oohs",
    soundbank: "lush-vocals",
  },
  54: {
    name: "Synth Voice",
    soundbank: "ahh-synth",
  },
  55: {
    name: "Orchestra Hit",
    soundbank: "string-orchestra-stacc",
  },
  56: {
    name: "Trumpet",
    soundbank: "trumpet-clean",
  },
  57: {
    name: "Trombone",
    soundbank: "trombone-hard",
  },
  58: {
    name: "Tuba",
    soundbank: "tuba",
  },
  59: {
    name: "Muted Trumpet",
    soundbank: "trumpet-straight-mute",
  },
  60: {
    name: "French Horn",
    soundbank: "french-horn",
  },
  61: {
    name: "Brass Section",
    soundbank: "full-brass",
  },
  62: {
    name: "Synth Brass 01",
    soundbank: "sunset-brass",
  },
  63: {
    name: "Synth Brass 02",
    soundbank: "fat-n-dirty",
  },
  64: {
    name: "Soprano Sax",
    soundbank: "alto-saxophone",
  },
  65: {
    name: "Alto Sax",
    soundbank: "alto-saxophone",
  },
  66: {
    name: "Tenor Sax",
    soundbank: "tenor-saxophone",
  },
  67: {
    name: "Baritone Sax",
    soundbank: "tenor-saxophone",
  },
  68: {
    name: "Oboe",
    soundbank: "oboe",
  },
  69: {
    name: "English Horn",
    soundbank: "french-horn",
  },
  70: {
    name: "Bassoon",
    soundbank: "bassoon",
  },
  71: {
    name: "Clarinet",
    soundbank: "clarinet",
  },
  72: {
    name: "Piccolo",
    soundbank: "flute",
  },
  73: {
    name: "Flute",
    soundbank: "flute",
  },
  74: {
    name: "Recorder",
    soundbank: "flute",
  },
  75: {
    name: "Pan Flute",
    soundbank: "pan-flute",
  },
  76: {
    name: "Blown Bottle",
    soundbank: "blown-bottle",
  },
  77: {
    name: "Shakuhachi",
    soundbank: "flute",
  },
  78: {
    name: "Whistle",
    soundbank: "whistle",
  },
  79: {
    name: "Ocarina",
    soundbank: "blown-bottle",
  },
  80: {
    name: "Lead 01 (Square)",
    soundbank: "80s-square-lead",
  },
  81: {
    name: "Lead 02 (Sawtooth)",
    soundbank: "super-saw",
  },
  82: {
    name: "Lead 03 (calliope)",
    soundbank: "eyelash-synth",
  },
  83: {
    name: "Lead 04 (chiff)",
    soundbank: "fm-lead",
  },
  84: {
    name: "Lead 05 (charang)",
    soundbank: "future-pop-stab",
  },
  85: {
    name: "Lead 06 (Voice)",
    soundbank: "lush-vocals",
  },
  86: {
    name: "Lead 07 (Fifths)",
    soundbank: "dirty-porto-5th",
  },
  87: {
    name: "Lead 08 (Lead and Bass)",
    soundbank: "heavy-lead",
  },
  88: {
    name: "Pad 01 (New Age)",
    soundbank: "new-age-synth",
  },
  89: {
    name: "Pad 02 (Warm)",
    soundbank: "warm-pad",
  },
  90: {
    name: "Pad 03 (Polysynth)",
    soundbank: "retro-juno-pad",
  },
  91: {
    name: "Pad 04 (Choir)",
    soundbank: "choir-synth",
  },
  92: {
    name: "Pad 05 (Bowed)",
    soundbank: "borealis-pad",
  },
  93: {
    name: "Pad 06 (Metallic)",
    soundbank: "shadow-bells",
  },
  94: {
    name: "Pad 06 (Halo)",
    soundbank: "cloud-fluff",
  },
  95: {
    name: "Pad 06 (Sweep)",
    soundbank: "evolve-pad",
  },
  96: {
    name: "FX 01 (Rain)",
    soundbank: "blip-perc",
  },
  97: {
    name: "FX 02 (Soundtrack)",
    soundbank: "grand-piano",
  },
  98: {
    name: "FX 03 (Crystal)",
    soundbank: "swell-pad",
  },
  99: {
    name: "FX 04 (Atmosphere)",
    soundbank: "atmosphere-pad",
  },
  100: {
    name: "FX 05 (Brightness)",
    soundbank: "atmosphere-pad",
  },
  101: {
    name: "FX 06 (Goblins)",
    soundbank: "space-bot",
  },
  102: {
    name: "FX 07 (Echoes)",
    soundbank: "wailer-synth",
  },
  103: {
    name: "FX 07 (Sci-Fi)",
    soundbank: "general-midi-drums",
  },
  104: {
    name: "Sitar",
    soundbank: "sitar",
  },
  105: {
    name: "Banjo",
    soundbank: "banjo",
  },
  106: {
    name: "Shamisen",
    soundbank: "grand-piano",
  },
  107: {
    name: "Koto",
    soundbank: "koto",
  },
  108: {
    name: "Kalimba",
    soundbank: "kalimba",
  },
  109: {
    name: "Bag Pipe",
    soundbank: "bagpipe",
  },
  110: {
    name: "Fiddle",
    soundbank: "solo-violin",
  },
  111: {
    name: "Shanai",
    soundbank: "grand-piano",
  },
  112: {
    name: "Tinkle Bell",
    soundbank: "vibraphone",
  },
  113: {
    name: "Agogo",
    soundbank: "steel-drum",
  },
  114: {
    name: "Steel Drums",
    soundbank: "steel-drum",
  },
  115: {
    name: "Woodblock",
    soundbank: "clap-slap",
  },
  116: {
    name: "Taiko Drum",
    soundbank: "taiko",
  },
  117: {
    name: "Melodic Tom",
    soundbank: "blip-perc",
  },
  118: {
    name: "Synth Drum",
    soundbank: "general-midi-drums-hiphop",
  },
  119: {
    name: "Reverse Cymbal",
    soundbank: "clap-slap",
  },
  120: {
    name: "Guitar Fret Noise",
    soundbank: "funk-guitar",
  },
  121: {
    name: "Breath Noise",
    soundbank: "blip-perc",
  },
  122: {
    name: "Seashore",
    soundbank: "blip-perc",
  },
  123: {
    name: "Bird Tweet",
    soundbank: "blip-perc",
  },
  124: {
    name: "Telephone Ring",
    soundbank: "general-midi-drums",
  },
  125: {
    name: "Helicopter",
    soundbank: "copterorchestra",
  },
  126: {
    name: "Applause",
    soundbank: "clap-slap",
  },
  127: {
    name: "Gunshot",
    soundbank: "electro-splat",
  },
  "-1": {
    name: "Percussion",
    soundbank: "general-midi-drums",
  },
}

export const SOUNDBANK_TO_PROGRAM_CHANGE = {
  "12-string-guitar": 25,
  "606-kit": -1,
  "62-p-bass": 33,
  "8-bit-chiptune-kit": -1,
  "808-bass": 38,
  "808-kick": 38,
  "808-kit": -1,
  "808-saturated-bass": 38,
  "80s-square-lead": 80,
  "909-kit": -1,
  "abstract-hip-hop-kit": -1,
  accordion: 21,
  "acid-bass": 38,
  "acid-hip-hop-creators-kit": -1,
  "acoustic-bass-legato": 32,
  "acoustic-bass-staccato": 32,
  "acoustic-guitar": 24,
  "afro-cuban-percussion": -1,
  "afrobeat-creators-kit-01": -1,
  "afrobeat-creators-kit-02": -1,
  "ahh-synth": 52,
  "airy-keys": 90,
  "alto-saxophone": 65,
  "ambient-lead": 89,
  "analog-desk": 38,
  "arcade-lead": 80,
  "arp-sequencer": -1,
  "atlanta-hip-hop-kit": -1,
  atlantispad: 88,
  "atmosphere-pad": 88,
  "attack-bass": 38,
  "b3-hammond": 18,
  bagpipe: 109,
  "ballad-kit": -1,
  banjo: 105,
  "bass-lead": 38,
  "basses-long-bows": 43,
  "basses-pizzicato": 45,
  "basses-short-bows": 44,
  "basses-tremolo": 44,
  bassoon: 70,
  "bedroom-beats-creators-kit": -1,
  "bedroom-kit": -1,
  "beginning-lead": 80,
  bells: 112,
  "berlin-lead": 93,
  "big-synth-lead": 87,
  "black-cat-creators-kit": -1,
  "black-noise-house-creators-kit": -1,
  "blip-perc": 117,
  "blown-bottle": 76,
  "blues-kit": -1,
  "bodyrocking-bass": 38,
  "boog-bass": 38,
  "boom-bap-creators-kit": -1,
  "boom-bap-kit-2": -1,
  "boom-bap-kit": -1,
  "borealis-pad": 90,
  "bounce-creators-kit": -1,
  "bouzouki-hard": 105,
  "bouzouki-soft": 105,
  "bright-piano": 1,
  "brush-kit": -1,
  "bubblegum-pop-creators-kit": -1,
  "bubblegum-trap-creators-kit": -1,
  "car-stereo": 38,
  "cat-pad": -1,
  "cello-section": 42,
  "cellos-pizzicato": 45,
  "cellos-short-bows": 42,
  "cellos-tremolo": 44,
  "cheeky-boom": 38,
  "chicago-house-vol-1": -1,
  "chicago-house-vol-2": -1,
  "chill-wave-kit": -1,
  "chill-wave-synth": 90,
  "chip-hat": 115,
  "chip-organ": 80,
  "choir-male-ahh": 52,
  "choir-synth": 91,
  "chonky-bass": 38,
  "chorus-organ": 18,
  "church-organ": 19,
  "cinematic-kit": -1,
  "cinematic-vast-kit": -1,
  "city-keys": 80,
  "clap-slap": 115,
  clarinet: 71,
  "classic-grime-creators-kit-01": -1,
  "classic-grime-creators-kit-02": -1,
  "classic-hip-hop-creators-kit": -1,
  "classic-house-kit": -1,
  "classic-metal-guitar": 30,
  "classic-metal-kit": -1,
  "classic-rock-kit": -1,
  "classic-rock-organ": 18,
  "classic-synth-bass": 38,
  "clean-5th-sine-organ": 87,
  "clean-guitar-hard": 27,
  "clean-guitar-muted": 28,
  "clean-guitar-soft": 27,
  "clean-guitar": 27,
  "clean-power-chord": 29,
  "clicky-bit": 38,
  "cloud-fluff": 89,
  "colossal-lead": 81,
  "compton-kit": -1,
  copterorchestra: 85,
  "country-kit": -1,
  "cuban-rhythm-creators-kit": -1,
  "dafunky-crunch": 80,
  "dance-lead": 81,
  "dark-grand": 0,
  "dark-hip-hop-kit": -1,
  "dark-organ": 16,
  "daylight-guitar": 26,
  "deep-house-bass": 38,
  "deep-house-synth": 89,
  "detuned-tapper": 38,
  "digital-dub-creators-kit": -1,
  "dirty-growl": 38,
  "dirty-legato-saw": 81,
  "dirty-porto-5th": 86,
  "dirty-wub": 81,
  divebomb: 38,
  "djent-guitar": 30,
  "dnb-kit": -1,
  "dont-stop-disco-creators-kit-vol-01": -1,
  "dont-stop-disco-creators-kit-vol-02": -1,
  "double-bass-section": 43,
  "dream-pad": 94,
  "dreamy-bells": 94,
  "drill-creators-kit-01": -1,
  "drill-creators-kit-02": -1,
  "drive-bass": 38,
  "drive-kit": -1,
  "dry-kit": -1,
  "duality-pad": 89,
  "dub-bass": 38,
  "dub-supersaw": 81,
  "dubstep-creators-kit": -1,
  "dubstep-kit": -1,
  "dubstep-lead": 80,
  "dumpy-kit": -1,
  "dustbin-acid": 38,
  "edm-creators-kit": -1,
  "edm-kit": -1,
  "electric-bass-legato": 33,
  "electric-bass-staccato": 33,
  "electric-piano": 4,
  "electro-pop-kit": -1,
  "electro-saw-bass": 38,
  "electro-splat": 123,
  "empire-kit": -1,
  "ethereal-techno-creator-kit": -1,
  "evolve-bass": 39,
  "evolve-pad": 95,
  "exceedingly-nice": 80,
  "eyelash-synth": 82,
  "fancy-bass": 38,
  "fanfare-organ": 16,
  "fat-90s-kit": -1,
  "fat-n-dirty": 81,
  "felt-piano": 0,
  "festive-creators-kit": -1,
  "festive-pad": -1,
  "finesse-pad": 91,
  "fizzy-interrupt": 38,
  flugelhorn: 56,
  flute: 73,
  "fm-gamelan": 14,
  "fm-keys": 5,
  "fm-lead": 87,
  "fm-mulch-bass": 38,
  "fm-pad": 93,
  "fm-quad-bass": 38,
  "fm-string": 50,
  "fm-tines": 4,
  "freestyle-kit": -1,
  "french-horn": 60,
  "full-brass-staccato": 61,
  "full-brass": 61,
  "full-strings-long-bows": 50,
  "full-strings-pizzicato": 45,
  "full-strings-short-bows": 50,
  "full-strings-tremolo": 44,
  "funk-guitar": 26,
  "funk-kit": -1,
  "funky-phat-lead": 81,
  "funky-slap": 36,
  "funky-tone": 7,
  "fusion-kit": -1,
  "future-bass-creators-kit": -1,
  "future-grunge-creators-kit": -1,
  "future-keys": 5,
  "future-pop-stab": 5,
  "future-redux-bass": 39,
  "future-sparkle-bass-creators-kit": -1,
  "future-trap-kit": -1,
  "g-funk-creators-kit": -1,
  "g-funk-lead": 81,
  "g-funk-sine": 87,
  "gameboy-creators-kit": -1,
  "general-midi-drums-hiphop": -1,
  "general-midi-drums": -1,
  "gfunk-saw": 81,
  "glitch-creators-kit": -1,
  "glitch-kit": -1,
  "glitch-lead": 80,
  glockenspiel: 9,
  "grand-piano": 0,
  "grime-bass": 38,
  "grime-creators-kit": -1,
  "groove-kit": -1,
  "growler-bass": 38,
  "grunge-glitch-creators-kit": -1,
  "guitar-power-chord": 30,
  "hacienda-bizarre-creators-kit": -1,
  "hacienda-order-creators-kit": -1,
  "hadda-bass": 38,
  "halcyon-5th": 86,
  "hammered-dulcimer": 15,
  "hard-rock-kit": -1,
  "hardcore-square-unison": 80,
  harmonica: 21,
  harp: 46,
  harpsichord: 6,
  "harris-wobble": 81,
  "heart-keys": 8,
  "heavy-lead": 87,
  "hip-hop-kit": -1,
  "honky-tonk-piano": 3,
  "hot-pop-kit": -1,
  "house-bass": 38,
  "house-chords": 86,
  "house-creator-kit": -1,
  "house-organ": 20,
  "hyper-fm": 80,
  "hyper-pop-synth": 81,
  "hyperbrite-piano": 1,
  "idm-kit": -1,
  "indie-rock-kit": -1,
  "industrial-creators-kit": -1,
  "industrial-kit": -1,
  "jacyn-riffs-1": 52,
  "james-alister-kit": -1,
  "jazz-bass": 33,
  "jazz-guitar": 26,
  "jazz-kit": -1,
  kalimba: 108,
  kantele: 107,
  "kaytran-pad": 89,
  "kick-bass": 38,
  koto: 107,
  "kpop-creators-kit": -1,
  "kpop-expanded-creators-kit": -1,
  "lately-bass": 38,
  "latin-creators-kit": -1,
  "latin-house-creators-kit": -1,
  "latin-kit": -1,
  "lcd-kit": -1,
  "lil-ukelele": 24,
  "live-kit": -1,
  "lo-fi-dreams-creators-kit": -1,
  "lo-fi-hip-hop-creators-kit": -1,
  "lo-fi-hop-kit": -1,
  "lo-fi-kit": -1,
  "lofi-creator-kit-ii": -1,
  "lofi-mallets": 89,
  "lofi-piano": 2,
  "lofi-saw": 87,
  "log-drum": 114,
  "lush-vocals": 91,
  "major-portamento": 0,
  marimba: 12,
  "matt-kit": -1,
  "minor-portamento": 0,
  "modern-breakbeat-creator-kit": -1,
  "modern-hip-hop-bass": 38,
  "modern-hip-hop-creators-kit": -1,
  "modern-metal-kit": -1,
  "moog-bass": 38,
  "moombahton-creators-kit": -1,
  "motorcity-kit": -1,
  "movie-pad": 89,
  nails: 38,
  "natty-kit": -1,
  "neo-soul-pad": 88,
  "neptunian-kit": -1,
  "new-age-synth": 88,
  "new-breed-clav": 6,
  "new-wave-kit": -1,
  "nifty-kit": -1,
  "noir-chord": 87,
  "nu-disco-bass": 36,
  "nu-house-kit": -1,
  "nylon-guitar": 24,
  oboe: 68,
  "ocean-pad": 89,
  "ol-dusty": 92,
  "old-school-breakbeat-creators-kit": -1,
  "organic-pop-creators-kit": -1,
  otamatone: 54,
  "overdriven-guitar": 29,
  "overdriven-power-chord": 29,
  "pan-flute": 75,
  "pant-flapper": 87,
  paper: 38,
  "party-bass": 38,
  "party-pop-creators-kit": -1,
  "percussion-plonk": -1,
  "phonk-bell-dirty": 118,
  "phonk-bell": 118,
  pike: 87,
  "pillow-kit": -1,
  "plucked-lead": 80,
  "plucked-vaporbass": 38,
  "pop-rock-kit": -1,
  "porto-reese-bass": 38,
  "post-punk-kit": -1,
  "prince-kit": -1,
  "pumped-up-bass": 33,
  "pumping-anthem": 95,
  "punchy-jazz-bass": 33,
  "punchy-kit": -1,
  "puppet-pad": -1,
  "raw-kit": -1,
  "reggae-kit": -1,
  "retro-bass": 38,
  "retro-future-synth-creators-kit": -1,
  "retro-juno-pad": 89,
  "retro-pick-bass": 33,
  "retro-synth-brass": 62,
  rhodes: 5,
  "rhythm-partner": 5,
  "ripped-cabinet": 38,
  "rnb-creators-kit-01": -1,
  "rnb-creators-kit-02": -1,
  "rnb-kit": -1,
  "rock-kit": -1,
  "rock-organ": 18,
  "roddy-rich-creators-kit": -1,
  "rumble-bass": 38,
  sawsine: 81,
  "scary-sound-pad": 121,
  "seamless-pad": 89,
  "sfx-firearm": 127,
  "sfx-pad": -1,
  "shadow-bells": 93,
  "shadow-soft": 89,
  "simple-organ": 20,
  "sine-bass": 38,
  "sinister-creators-kit": -1,
  "sinister-trap": -1,
  sitar: 104,
  "slap-bass": 36,
  "smooth-brass-pad": 62,
  "smooth-fuzzy-pad": 91,
  "smooth-reese-bass": 38,
  "soft-bells": 80,
  "soft-pad": 94,
  "soft-sine-bass": 38,
  "solid-bass": 39,
  "solo-female-ahh": 52,
  "solo-violin": 40,
  "soul-kit": -1,
  "space-bot": 54,
  "space-juice-creators-kit": -1,
  "space-wobble": 38,
  "sparkle-keys": 87,
  "sparkling-acoustic": 25,
  "square-sub-bass": 38,
  "steel-drum": 114,
  "steve-jackson-kit": -1,
  "stratosphere-pad": 95,
  "string-orchestra": 48,
  "string-orchestra-pizz": 45,
  "string-orchestra-stacc": 48,
  "string-pad": 50,
  "studio-grand": 0,
  "studio-harpsichord": 6,
  "sub-rattle": 38,
  "sub-shaker": 38,
  "sub-texture": 38,
  "subtle-rattle": 38,
  "sun-pad": 90,
  "sunset-brass": 62,
  "super-saw": 81,
  "swell-pad": 95,
  "synth-kit": -1,
  "synth-organ": 20,
  "synth-strings": 50,
  "synthpop-creators-kit": -1,
  taiko: 116,
  "tape-sawtooth": 81,
  "techno-brute-kit": -1,
  "techno-throwback-kit": -1,
  "tenor-saxophone": 66,
  "textures-kit": -1,
  "thick-air-pad": 88,
  "thick-dust": 38,
  "thriller-bass": 38,
  "thump-kit": -1,
  timpani: 47,
  "tokyo-sunset": 89,
  "trance-pluck": 81,
  "trap-creators-kit-01": -1,
  "trap-creators-kit-02": -1,
  "trap-kit": -1,
  "trash-kit": -1,
  "trip-hop-creators-kit": -1,
  trombone: 57,
  "trombone-hard": 57,
  "trombone-soft": 57,
  "trombone-staccato": 57,
  "tropical-house-bass": 38,
  "tropical-house-creators-kit": -1,
  trumpet: 56,
  "trumpet-clean": 56,
  "trumpet-cup-mute": 56,
  "trumpet-harmon-mute": 56,
  "trumpet-staccato": 56,
  "trumpet-straight-mute": 56,
  tuba: 58,
  "tuba-legato": 58,
  "tuba-staccato": 58,
  "tubular-bells": 14,
  "twang-guitar": 27,
  "two-saw-detune": 81,
  "uber-lead": 80,
  ukelele: 24,
  "ultra-808": -1,
  "uncommon-creators-kit": -1,
  "underground-trap-creators-kit": -1,
  "upright-piano": 1,
  "vapor-lead": 81,
  vibraphone: 11,
  "vintage-hip-hop-kit": -1,
  "vintage-pad": 95,
  "vintage-pop-stabs": 38,
  "vintage-swell-bass": 39,
  vintagefour: 87,
  "viola-section": 41,
  "viola-solo-pizzicato": 45,
  "viola-solo-tremolo": 44,
  "violas-long-bows": 41,
  "violas-short-bows": 41,
  "violas-tremolo": 44,
  "violin-section": 40,
  "violin-solo-pizzicato": 45,
  "violin-solo-tremolo": 44,
  "violins-pizzicato": 45,
  "vista-synth": 81,
  "wah-rnb-pad": 89,
  "wailer-synth": 89,
  "warm-pad": 89,
  "welcome-pad": 93,
  whistle: 78,
  wurlitzer: 5,
  xylophone: 13,
  "zoom-r2d2": 38,
}
